name: python-ci
on:
  push:
    branches: [main]
  pull_request:
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: python -m pip install -U pip
      - run: pip install -r requirements-dev.txt
      - run: black --check .
      - run: ruff check .
      # Uncomment below when you add tests
      # - run: pip install -r requirements.txt
      # - run: pytest -q
